### ISSUE TITLE
ASP MVC multitenant on core

### ISSUE THREAD

**Issue by mach37** [pkellner/pluralsight-multitenantaspnet#1]
Hi, I got the pluralsight class to implement multitenant, but unable to get it working on the core or even the basic ASP MVC 5, can you please update the sample to help.

**Comment by pkellner** [comment]
Core is pretty different. I've not yet put work into updating this repo.  Maybe someday.

**Comment by mach37** [comment]
Ok, this/ MVC 5 is fine but any chance you can do it in native Jquery, the choices in angular is mind-boggling, not to mention the additional work involved in maintaining the MVC in Angular.

**Comment by pkellner** [comment]
It's been a while but I thought I had some examples in JQuery? I agree about mind-boggling. I've moved on personally from angular to react which I like much better (less mind boggling)
